name: map_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you are planning to publish this package to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   google_maps_flutter: ^2.2.1 
#   google_maps_cluster_manager: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.2
  flutter_typeahead: ^4.0.0 # For the autocomplete search
  http: ^0.13.5 # For making HTTP requests


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
